# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: sim_control_message.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)




DESCRIPTOR = _descriptor.FileDescriptor(
  name='sim_control_message.proto',
  package='sim_control_message.msgs',
  serialized_pb='\n\x19sim_control_message.proto\x12\x18sim_control_message.msgs\"@\n\x11SimControlMessage\x12\x19\n\x11\x43onfigurationName\x18\x01 \x02(\t\x12\x10\n\x08GaitName\x18\x02 \x01(\t')




_SIMCONTROLMESSAGE = _descriptor.Descriptor(
  name='SimControlMessage',
  full_name='sim_control_message.msgs.SimControlMessage',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ConfigurationName', full_name='sim_control_message.msgs.SimControlMessage.ConfigurationName', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='GaitName', full_name='sim_control_message.msgs.SimControlMessage.GaitName', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=unicode("", "utf-8"),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  serialized_start=55,
  serialized_end=119,
)

DESCRIPTOR.message_types_by_name['SimControlMessage'] = _SIMCONTROLMESSAGE

class SimControlMessage(_message.Message):
  __metaclass__ = _reflection.GeneratedProtocolMessageType
  DESCRIPTOR = _SIMCONTROLMESSAGE

  # @@protoc_insertion_point(class_scope:sim_control_message.msgs.SimControlMessage)


# @@protoc_insertion_point(module_scope)
